@baseUrl = http://localhost:{{$dotenv PORT}}/api

# @name GetPosts

GET {{baseUrl}}/post/
###

GET {{baseUrl}}/user/{{postAuthor}}
###
POST {{baseUrl}}/auth/signup
content-type: application/json

{
  "username": "samzanca1",
  "password":"password123"
}
###

POST {{baseUrl}}/auth/signin
content-type: application/json

{
  "username": "samzanca1",
  "password":"password123"
}